### ISSUE TITLE
Options doesnt work

### ISSUE THREAD

**Issue by reyard** [funkydude/BasicMinimap#100]
## Describe the problem

GatherMate 2 Options Doesn't work, I can't put track only when I track herbs or minerals or excavation.
### What steps will reproduce the problem?

1.  Go gathermate 2 options
2.  pick only track when I track minerals
3.  Track minerals
4. Doesnt work

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

**Track when I track Minerals - CHECK MINIMAP**
![WoWScrnShot_081924_013429](https://github.com/user-attachments/assets/fb5a09a7-3c49-4f55-b833-a143ae5389ea)
**Always track - CHECK MINIMAP**
![WoWScrnShot_081924_013439](https://github.com/user-attachments/assets/3cb38be2-f037-4295-aca6-c94c05a75ff9)

### What version of the addon are you using? (Stating 'latest' is not useful)
Last version 1.49.1

### Do you have an error log of what happened?
No error log

### Any additional information? (example: WoW language if not English)
Wow, Languaje Spanish

**Comment by funkydude** [comment]
Stop taking drugs. This isn't the Gathermate addon.
