### ISSUE TITLE
BMM options not available

### ISSUE THREAD

**Issue by Velarax** [funkydude/BasicMinimap#101]
### What steps will reproduce the problem?

1.  /bmm does not pull up options and am unable to scale or move bmm
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
August 2 2024

### Do you have an error log of what happened?

6x BasicMinimap/BasicMinimap.lua:24: attempt to call global 'EnableAddOn' (a nil value)
[string "@BasicMinimap/BasicMinimap.lua"]:24: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5468: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5414>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5120: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5119>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5156: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
(*temporary) = nil
(*temporary) = "BasicMinimap_Options"
(*temporary) = "attempt to call global 'EnableAddOn' (a nil value)"
name = "BasicMinimap"

**Comment by funkydude** [comment]
You're using an old version, please update to the latest release.

**Comment by Velarax** [comment]
If there is a release post 8/2/24 it's not available on Curse or anywhere else I can find.  Thanks for your time.

**Comment by funkydude** [comment]
Sorry, what I meant is the version you claim to be using isn't actually what you are running.
