### ISSUE TITLE
zone text and clock styling breaks when any addon is enabled/disabled and UI is reloaded

### ISSUE THREAD

**Issue by mvkx** [funkydude/BasicMinimap#104]
## Describe the problem
Zone text and clock styling fails and day/night indicator isn't hidden after any addon is enabled/disabled and UI is reloaded with the "Reload UI" button in addon list. Reloading UI doesn't help, but reloggging will fix the issue. 

### What steps will reproduce the problem?

1.  BMM and some other addon present
2.  Enable or disable the other addon from addon list and click "Reload UI"

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
Before:
![Screenshot 2024-10-02 102439](https://github.com/user-attachments/assets/12209385-fec3-4abc-a7c0-6b9ddaa5a105)
Addons list:
![Screenshot 2024-10-02 102724](https://github.com/user-attachments/assets/8ed3f6a0-591a-4c18-8ca5-64dd38e4dcf0)
After "Bugsack" is enabled and UI is reloaded:
![Screenshot 2024-10-02 102848](https://github.com/user-attachments/assets/51ecbab7-bbb8-4998-8b7a-2efc2f4b53eb)

### What version of the addon are you using? (Stating 'latest' is not useful)
Version: v11.0.4

### Do you have an error log of what happened?
Bugsack shows this:

```
4x BasicMinimap/BasicMinimap_Vanilla.lua:636: attempt to index global 'MiniMapTrackingFrame' (a nil value)
[string "@BasicMinimap/BasicMinimap_Vanilla.lua"]:636: in function <BasicMinimap/BasicMinimap_Vanilla.lua:498>
[string "@BasicMinimap/BasicMinimap_Vanilla.lua"]:786: in function <BasicMinimap/BasicMinimap_Vanilla.lua:777>

Locals:
self = BasicMinimap {
 blizzButtonNicknames = <table> {
 }
 backdrop = Texture {
 }
 db = <table> {
 }
 mask = MaskTexture {
 }
}
fullMinimapSize = 145
mask = MaskTexture {
}
shape = "ROUND"
icon = 133939
(*temporary) = nil
(*temporary) = nil
(*temporary) = 133939
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'MiniMapTrackingFrame' (a nil value)"
backdrop = Texture {
}
backdropFrame = Frame {
}
frame = BasicMinimap {
 blizzButtonNicknames = <table> {
 }
 backdrop = Texture {
 }
 db = <table> {
 }
 mask = MaskTexture {
 }
}
Minimap = Minimap {
 timer = 0
}
ldbi = <table> {
 callbacks = <table> {
 }
 radius = 5
 loggedIn = true
 tooltip = LibDBIconTooltip {
 }
 objects = <table> {
 }
 callbackRegistered = true
}
blizzButtonNicknames = <table> {
 zoomIn = MinimapZoomIn {
 }
 mail = MiniMapMailFrame {
 }
 lfg = MiniMapLFGFrame {
 }
 zoomOut = MinimapZoomOut {
 }
 pvp = MiniMapBattlefieldFrame {
 }
}
```

**Comment by funkydude** [comment]
Fixed in https://github.com/funkydude/BasicMinimap/commit/96426aba0fc0aa92fda3da45901b4a9328a1bd97
