### ISSUE TITLE
Era - Lua error -> characters with tracking abilities.

### ISSUE THREAD

**Issue by boxcutter411** [funkydude/BasicMinimap#105]
## Describe the problem
Seems to only occur when the character has a tracking ability (eg hunters, herbalists etc)  The tracking icon is not visible, the blizz clock appears and right click functionality to open the map fails.  Classes without tracking abilities don't seem to throw the error.

### What steps will reproduce the problem?

1.  Character with tracking ability
2.  Trigger ability
3.  Reload

### What version of the addon are you using? (Stating 'latest' is not useful)
v11.0.4

### Do you have an error log of what happened?

BasicMinimap/BasicMinimap_Vanilla.lua:636: attempt to index global 'MiniMapTrackingFrame' (a nil value)
[string "@BasicMinimap/BasicMinimap_Vanilla.lua"]:636: in function <BasicMinimap/BasicMinimap_Vanilla.lua:498>
[string "@BasicMinimap/BasicMinimap_Vanilla.lua"]:786: in function <BasicMinimap/BasicMinimap_Vanilla.lua:777>

Locals:
self = BasicMinimap {
 blizzButtonNicknames = <table> {
 }
 backdrop = Texture {
 }
 db = <table> {
 }
 mask = MaskTexture {
 }
}
fullMinimapSize = 145
mask = MaskTexture {
}
shape = "SQUARE"
icon = 133939
(*temporary) = nil
(*temporary) = nil
(*temporary) = 133939
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = LibDBIcon10_Masque {
 fadeOut = AnimationGroup {
 }
 dataObject = <table> {
 }
 isMouseDown = false
 db = <table> {
 }
 icon = Texture {
 }
}
(*temporary) = 240
(*temporary) = "attempt to index global 'MiniMapTrackingFrame' (a nil value)"
backdrop = Texture {
}
backdropFrame = Frame {
}
frame = BasicMinimap {
 blizzButtonNicknames = <table> {
 }
 backdrop = Texture {
 }
 db = <table> {
 }
 mask = MaskTexture {
 }
}
Minimap = Minimap {
 timer = 0
}
ldbi = <table> {
 callbacks = <table> {
 }
 loggedIn = true
 radius = 5
 tooltip = LibDBIconTooltip {
 }
 objects = <table> {
 }
 callbackRegistered = true
}
blizzButtonNicknames = <table> {
 zoomIn = MinimapZoomIn {
 }
 mail = MiniMapMailFrame {
 }
 lfg = MiniMapLFGFrame {
 }
 zoomOut = MinimapZoomOut {
 }
 pvp = MiniMapBattlefieldFrame {
 }
}

**Comment by funkydude** [comment]
Fixed, thanks!

**Comment by nteetor** [comment]
Any idea when a version with this fix will be released?

**Comment by funkydude** [comment]
3 weeks ago, when I posted the comment.
