### ISSUE TITLE
BasicMiniMap: Profession Tracking Button Broken

### ISSUE THREAD

**Issue by 1ManRiot** [funkydude/BasicMinimap#109]
## Describe the problem
The profession resources tracking button (for mining and herb) does not stay anchored to the minimap when its moved. The button for finding ore is stuck at the top right of the screen with no options to move it.

Edit: When the profession tracking button was anchoring correctly; I noticed that if you used the ROUND minimap the harvesting tracking icon does not align with the round map shape and would anchor itself away from the minimap as if it was a square.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![WoWScrnShot_112024_103059](https://github.com/user-attachments/assets/f0d3fd95-c48e-435d-b7d4-672bbab35023)

### What version of the addon are you using? (Stating 'latest' is not useful)
11.0.6 & 11.0.7

### Do you have an error log of what happened?
no errors, just incorrectly functioning

**Comment by Vakke** [comment]
Having the same issue.

I use the square minimap option on  the default position and the profession tracking button is fixed and cannot be moved. It sits almost in the middle of minimap and blocks the view. I use default blizz ui with dominos actionbars so it's not an ElvUI problem either.

Hopefully this could be fixed!

**Comment by Syndr34** [comment]
I am having same issue. See attached.
![Finding Tracker Unmoveable](https://github.com/user-attachments/assets/bad8636a-51d8-460d-87ff-7402ebc710e6)

**Comment by funkydude** [comment]
Support for moving it added in latest update.

**Comment by Syndr34** [comment]
Awesome. Thank you very much.
