### ISSUE TITLE
Possible to scale map smaller?

### ISSUE THREAD

**Issue by Fizgig1973** [funkydude/BasicMinimap#12]
With the latest change I noticed that the minimap has gotten larger, even when set at the lowest scale (140). 

Is it possible to allow it go lower than that? I've used BMM for years because it is just what I need without all the extras. 

The blank square is where BMM sat prior to the latest patch.
![image](https://user-images.githubusercontent.com/37719752/43739604-790d9b32-997d-11e8-91df-b6bc29c5e70f.png)

**Comment by malikoth** [comment]
I'm sorry -- this is too funny...  I think the new sizes are too small, you think they're too big.  I think the clear takeaway is that we liked and used the ability to scale, not just adjust the size, of the minimap.

**Comment by funkydude** [comment]
Fixed in be25685206a9f4b952378d548627fa5e8f85c611
