### ISSUE TITLE
Instance difficulty text

### ISSUE THREAD

**Issue by ehern87** [funkydude/BasicMinimap#13]
Would it be possible to get a simple text indicator for instance difficulty similar to bdMinimap (bottom right)?

![image](https://user-images.githubusercontent.com/16833/43990084-51113fc4-9d4e-11e8-8d2d-54174c446b58.png)

**Comment by funkydude** [comment]
I don't see the benefit. This is frivolous **static** information, it never changes like the zone text or clock. Having a permanent display for such information is not good design. It's eye candy that gets boring after a while.
