### ISSUE TITLE
Option: Clock Position

### ISSUE THREAD

**Issue by dethleffson** [funkydude/BasicMinimap#16]
![image](https://user-images.githubusercontent.com/8402468/44028819-6f0a53a4-9efb-11e8-9b43-efccdab36f48.png)

I would really like to have the option to move and position my clock as on my screenshot. I needed to modify your LUA file and now I need to do it everytime I am going to update your addon :)

Sidenote: Thank you so much for doing this!

**Comment by funkydude** [comment]
Added in https://github.com/funkydude/BasicMinimap/commit/2955b41c0f7eaf616a25c875588725aa00d632f9
