### ISSUE TITLE
Option: Disable Clock/Location/etc

### ISSUE THREAD

**Issue by dethleffson** [funkydude/BasicMinimap#17]
![image](https://user-images.githubusercontent.com/8402468/44028819-6f0a53a4-9efb-11e8-9b43-efccdab36f48.png)

I would really like to have the option to disable the Location and clock or (as the other issue), move them around as I want to :) 

I needed to modify your LUA file and now I need to do it everytime I am going to update your addon :)

Again, thank you! <3

**Comment by funkydude** [comment]
Don't waste my time opening issues without looking at the options.
