### ISSUE TITLE
Option: Bring in the date

### ISSUE THREAD

**Issue by dethleffson** [funkydude/BasicMinimap#18]
![image](https://user-images.githubusercontent.com/8402468/44028819-6f0a53a4-9efb-11e8-9b43-efccdab36f48.png)

Yes, again the same screenshot. At the moment I placed a broker below my map. It would be awesome to have the option to turn the actual date on or off and position it freely (like in the screenshot). If I am pressing the button, the actual calendar is opening.

Much love <3

**Comment by funkydude** [comment]
No.
