### ISSUE TITLE
Clock text no longer displays

### ISSUE THREAD

**Issue by thisSIDEofRANDOM** [funkydude/BasicMinimap#19]
Curious if you have seen any addon conflicts as after the most recent update my clock text stopped appearing on addon load.

**Comment by funkydude** [comment]
Have you tested with only BM enabled? Do you have MoveAnything installed and have you tried disabling it?

**Comment by funkydude** [comment]
Can you clarify what the issue was?

**Comment by Kamprov** [comment]
Hey @funkydude , sorry for digging this issue back up but I recently had a similar problem and wanted to give you some details on what caused it for me.

This is how my minimap looked when I logged on:
![image](https://user-images.githubusercontent.com/10644248/99858357-aa270880-2b8d-11eb-87d2-c040f322b0a2.png)

I have both "Clock" and "Coordinates" turned on and they showed up as those double dots.

To fix it temporarily I could either do a /reload or go to options and change the Font Size parameter for both (I was selecting the number window and confirming with Enter). But if I close WoW and start it back up I again could see only those dots.

If I disabled all other addons the text would display as it should (only bigger in size). I found that it was Shadowed Unit Frames that was causing the problem, or specifically the Font I used. I had used Myriad Condensed Web on both SUF and BasicMinimap. When I changed the font on BasicMinimap to Friz Quadrata TT (just an example, I guess any font that will be different from the one used in SUF will work) everything worked as it should.

**Comment by funkydude** [comment]
I cannot reproduce this issue @Kamprov despite following your steps.
I'll need you to recreate the issue again and attach your SavedVariables file to this ticket.
You can find this file here:
`\World of Warcraft\_retail_\WTF\Account\yourAccountName\SavedVariables\BasicMinimap.lua`

You should be able to drag the file straight onto this issue.

**Comment by Kamprov** [comment]
Sure, I changed the font back to Myriad Condensed Web, closed the game, and when I logged back on this is how it looked:
![image](https://user-images.githubusercontent.com/10644248/99880281-d46ed980-2c12-11eb-8140-3ceb6d2c7c6f.png)

Here's the file. Changed the extension to .txt because .lua couldn't be uploaded here.
[BasicMinimap.txt](https://github.com/funkydude/BasicMinimap/files/5577813/BasicMinimap.txt)

**Comment by funkydude** [comment]
Thanks very much for attaching that.
Unfortunately it seems to be a bug in WoW itself.
I've worked around it in the latest release but hopefully this will be enough information for me to pass to Blizzard to look into it.
