### ISSUE TITLE
Movable Minimap buttons...??

### ISSUE THREAD

**Issue by WEEZYPEANUT** [funkydude/BasicMinimap#22]
This addon is ‘almost’perfect, the ability to scale and sizethe map is fantastic unlike others.
However for me the number 1 glaring issue is the fact you cannot move some of the buttons around the map such as the mail box, mission button, lfg button, in other words the blizzard ones. almost every other map addon lets you do this, which is so aggravating.

Two other more minor points would be the ability to move the position of the clock and zone name. and the ability for a flashing node option that addons like sexymap and mappy use.

**Comment by TSSchoof** [comment]
Indeed, the option to move mail / tracking icons would make this addon perfect. :)

**Comment by funkydude** [comment]
@TSSchoof 
> tracking icons

There is no tracking button when using this addon.

**Comment by funkydude** [comment]
Closing as a duplicate.
