### ISSUE TITLE
BMM for Classic Not Saving Settings

### ISSUE THREAD

**Issue by Apoxiosis** [funkydude/BasicMinimap#26]
BMM for Classic not Retaining Settings through /reload or relogs. 

I see a post where another user was having the same issue, which he said was caused by another addon but didnt specify which. If it is, what would your insights be on what another addon would have to be doing to reset BMM settings between /reloads?

**Comment by funkydude** [comment]
Works fine for me. You're probably not using the classic specific version of BM.
