### ISSUE TITLE
Zone text hidden by other addons?

### ISSUE THREAD

**Issue by Cleric670** [funkydude/BasicMinimap#27]
For some reason when you use Bartender4 and this addon at the same time the Zone Text above the map disappears? Bartender4 doesn't use the zone text for anything so I'm not totally sure why this happens.

**Comment by funkydude** [comment]
I use both fine. Probably a different addon. Try using only BasicMinimap.

**Comment by funkydude** [comment]
No response explaining what addon was responsible, closing.
