### ISSUE TITLE
How do you move it?

### ISSUE THREAD

**Issue by JeffreySWhitmore** [funkydude/BasicMinimap#28]
Clicking Lock to be Off doesn't work, tried alt, ctrl, shift etc

**Comment by funkydude** [comment]
You move it by simply dragging it when it's unlocked. If that's not working, you have another addon interfering. Try disabling your other addons and see if it works then. Let me know what addon was responsible.

**Comment by funkydude** [comment]
No response explaining what addon was responsible, closing.
