### ISSUE TITLE
Add an option to hide coords

### ISSUE THREAD

**Issue by Shimiya** [funkydude/BasicMinimap#32]
Hi,

Could you, please, add an option to hide coords ?

Thanks for reading.

**Comment by funkydude** [comment]
What are you using for coordinates? Why do you prefer it?

**Comment by Shimiya** [comment]
![WoWScrnShot_091619_084825](https://user-images.githubusercontent.com/42399315/64939108-65ecf980-d860-11e9-9894-467c7f9c1243.jpg)
(Screenshot with BasicMinimap-v8.2.0)

I already show coords/zone name (with Broker Everything) in my broker bar (with Bazooka) just above my minimap.

I just keep BasicMinimap "basic and clean" and except Missions button (displaced by Moveanything) I do not use any of the options.

Even the class colored border is made by hand with Skinner because I can set a texture on it.

**Comment by Shimiya** [comment]
The last update allow to move it and/or hide it by Alpha setting, It's a good workaround for me and I think that don't need more work from your side.

Thanks !

**Comment by funkydude** [comment]
Added in 8e48f44930c7908850b74a24393720e43443c336
