### ISSUE TITLE
Paladin Sense Undead Icon

### ISSUE THREAD

**Issue by AstroCat00** [funkydude/BasicMinimap#33]
Can we place have control of the Paladin Sense Undead Icon on the minimap? It is always displayed and no way to move it.

Thanks!

**Comment by funkydude** [comment]
No clue what you're talking about. Not enough detail and no screenshot.

**Comment by AstroCat00** [comment]
Sorry, when the Paladin casts Sense Undead a round minimap Tracking icon appears in the upper left of the minimap. It does not follow the addons minimap behavior and there is no way to control it. I was wondering if BM could control the Tracking minimap icon.

https://wow.gamepedia.com/Sense_Undead

**Comment by funkydude** [comment]
Your issue is with classic. It's really not that hard to give full information, especially something that critical, when opening your issue. It saves a lot of time.

**Comment by funkydude** [comment]
Closing as a duplicate.
