### ISSUE TITLE
Minimap addon buttons not controlled

### ISSUE THREAD

**Issue by AstroCat00** [funkydude/BasicMinimap#34]
Sorry, another one... these mods put a buttons on the minimap, but BM doesn't seem to have any control over them. They are always there and only moves in a small circle like the original minimap.

https://www.curseforge.com/wow/addons/lorehelper
https://www.curseforge.com/wow/addons/itemrack-classic

**Comment by funkydude** [comment]
Not a BM issue. If an addon doesn't create its minimap button using the [LibDBIcon](https://www.curseforge.com/wow/addons/libdbicon-1-0) community library, it won't be controlled by BM.
