### ISSUE TITLE
Can't hide unread mail icon

### ISSUE THREAD

**Issue by AlexFolland** [funkydude/BasicMinimap#38]
This addon is almost a complete replacement for Chinchilla in my particular setup on Classic.  The only thing I can't do that I want to is hide the unread mail icon, which I have a libdatabroker addon (Aanye Mail) for.

![image](https://user-images.githubusercontent.com/601517/65434255-5f680000-ddd3-11e9-8cfb-80dd1bbbc3bb.png)

Thanks for this sweet addon!

**Comment by funkydude** [comment]
You can hide the icon easily by opening your mail :)

**Comment by AlexFolland** [comment]
I have a different display for unread mail, which is a libdatabroker addon called Aanye Mail.  Until the mail is read, the icon on the minimap is redundant information.

What I was trying to say is that this addon can almost do as well as Chinchilla at being a basic minimal minimap addon that shows nothing but the minimap, except it can't hide the unread mail icon that is anchored to the minimap until read, even if a user wants to hide it because they have a separate display.  This issue is still relevant.

**Comment by funkydude** [comment]
I will need to review the list of all buttons in the hide section at some point.
