### ISSUE TITLE
Possible to move it independently of quest tracker?

### ISSUE THREAD

**Issue by wheatbread** [funkydude/BasicMinimap#40]
Thank you for the update!

Might it be possible to move it independently of the quest tracker window?

Currently when I drag the minimap to the bottom right corner of the screen, the quest tracker window comes with it.  I actually don't remember it doing this before?  which is why I ask. <3

**Comment by funkydude** [comment]
It already moves independently of the quest tracker, you even stated this yourself that you don't remember the addon doing this.

So basically, you've installed some other addon that's breaking it. Disable all your other addons and it will probably work fine. Then re-enable them in batches to find the culprit. Post back here with what was causing the problem so others can see.

**Comment by funkydude** [comment]
No response, closing.
