### ISSUE TITLE
Minimap occasionally moves itself when /reload is used

### ISSUE THREAD

**Issue by MarkKehn** [funkydude/BasicMinimap#42]
I have been having a couple of problems with addons recently. This is one of them, and then I got two others also throwing errors too. When I am trying to fix the other addon errors I sometimes do a /reload.

One of the issues I have been having with Basic Minimap lately besides the other one I posted below is that when I do a /reload to try and fix another addon, Basic Minimap occasionally moves itself to the top-left corner of the screen and I have to keep moving it back to the right side where I want it.

It does not throw an error when it decides to move itself, but it gets frustrating when it happens. I don't know why it's doing that. The other two addons I am having issues with have nothing to do with maps/minimaps or even minimap buttons so I don't know why the minimap moves itself.

**Comment by funkydude** [comment]
You've obviously got another addon conflicting with it. Disable all your other addons and try again.

**Comment by funkydude** [comment]
No response, closing.
