### ISSUE TITLE
Allow moving of Find Herbs/Minerals/Chests

### ISSUE THREAD

**Issue by BreakBB** [funkydude/BasicMinimap#48]
It would be awesome to be able to move the default minimap icons like "Find Herbs".

Currently these can't be moved and cover the minimap:

![grafik](https://user-images.githubusercontent.com/33514570/95362178-02e85d80-08ce-11eb-9ad9-393120e6e8a1.png)

**Comment by funkydude** [comment]
Closing as a duplicate
