### ISSUE TITLE
calendar option on minimap

### ISSUE THREAD

**Issue by Kosiee** [funkydude/BasicMinimap#49]
Hey - firstly thanks a lot for the addon. I was wondering if it would be possible to add an option in to enable/disable the calendar in WoW? Would be good if you could add that along with the option to re-position the icon anywhere on the minimap.

Thanks!

**Comment by funkydude** [comment]
The calendar is already disabled and only shows when you have a pending invite. Maybe you can elaborate on the issue you have?

**Comment by Kosiee** [comment]
Hey thanks for your reply. Apologies if I wasn't clear, I don't have any issue with the addon as such, I was just wondering if it was possible to add the calendar icon on the minimap permanently. However, having said that I have just realized you can right-click on the mini map and it will open your calendar so my request is probably somewhat irrelevant now haha. Thanks though!

**Comment by funkydude** [comment]
No problem. The `clicks` section in the options allows you to use mouse buttons so you can keep more things hidden but still access it.
