### ISSUE TITLE
Mail & Calendar Icon

### ISSUE THREAD

**Issue by DasKuddel** [funkydude/BasicMinimap#51]
Hey, is there a Way to move Mail & Calendar Icon pls? I cant put the map in the right corner, because i cant see the icons than. :(

![image](https://user-images.githubusercontent.com/16833/97264048-16774c00-181c-11eb-8c39-2ba27a2f08b1.png)

Using Version v9.0.3

**Comment by funkydude** [comment]
This addon already hides the calendar button so you've got some other addon force showing it.

In regards to the mail icon, I've created a separate issue about moving icons.
