### ISSUE TITLE
Moving minimap buttons

### ISSUE THREAD

**Issue by funkydude** [funkydude/BasicMinimap#52]
Addon buttons are already movable, but a lot of people would like to see the default Blizzard buttons be movable.

If you want to see this functionality you can thumbs up this post.

**Comment by wheatbread** [comment]
I would love this!  I have my minimap set to the lower right corner of my screen, and this means the LFG eye is halved and kind of hard to click.  Also means I don't get to see the nice timer that appears below the eye.

**Comment by Esionru** [comment]
![Снимок](https://user-images.githubusercontent.com/315414/97662860-f228a300-1a99-11eb-9761-96bd3a991bfa.PNG)
Please fix! :) thx for u addons

**Comment by slmcrs** [comment]
Agreed, the LFG eye in the corner doesn't look to goo when clock text is enabled, they end up overlapping.

**Comment by addonaddict** [comment]
yes i would love that change

**Comment by funkydude** [comment]
> 
> 
> Agreed, the LFG eye in the corner doesn't look to good when clock text is enabled, they end up overlapping.

The default position of the LFG button has been moved in the new update. This should make some people happier.

**Comment by Kosiee** [comment]
Has anything been added to the addon to allow us to move the buttons around? I'd like to be able to move the Missions button for example. Also, any chance we could see an option to also re-size these buttons as they are a little small for me. Thanks!

**Comment by klingo** [comment]
Would be great to be able to move the "new mail" indicator around.

**Comment by funkydude** [comment]
This is now available in the latest release for retail wow via a slider in the options. It may not be as cool as just dragging it like addon buttons but it gets the job done.
