### ISSUE TITLE
Compatibility with FarmHud

### ISSUE THREAD

**Issue by hizuro** [funkydude/BasicMinimap#54]
On enable FarmHud the backdropFrame from BasicMinimap is difficult to catch.
Please use the following function to help for a better cooperation between our addons. ;-)

```
if FarmHud then
    FarmHud:RegisterForeignAddOnObject( backdropFrame, "BasicMinimap")
end
```

For testing i've added this lines into Login( ) function.

Greetings
Hizuro

**Comment by funkydude** [comment]
Hi. I don't mind adding this, but I'd like to know what the problem is exactly.
Is this an issue with correctly restoring the Minimap to it's previous state when turning off FarmHud?

**Comment by hizuro** [comment]
The backdropFrame are moving with the Minimap in the middle of the screen when turning on FarmHud. The restoring doesn't make problems. More then backdropFrame are not necessary because all other elements are bound by SetPoint to the backdropFrame.
Alternative you give backdropFrame a name like BasicMinimapBackdrop and i can add it to my table anchoredFrames.

**Comment by hizuro** [comment]
It's okay. I found a way to get your backdropFrame with BasicMinimap.backdrop:GetParent().
/close
