### ISSUE TITLE
Error after reloading UI in Oribos Inn

### ISSUE THREAD

**Issue by Caedilla** [funkydude/BasicMinimap#56]
Following Lua Error after reloading UI when in the new Inn in Oribos. It doesn't occur on a fresh login, only after reloading UI. Haven't tested in other locations. 

1x BasicMinimap\BasicMinimap-v9.0.9.lua:352: attempt to call a nil value
[string "@BasicMinimap\BasicMinimap-v9.0.9.lua"]:352: in function `update'
[string "@BasicMinimap\BasicMinimap-v9.0.9.lua"]:356: in function <BasicMinimap\BasicMinimap.lua:280>
[string "@BasicMinimap\BasicMinimap-v9.0.9.lua"]:707: in function `?'
[string "@BasicMinimap\BasicMinimap-v9.0.9.lua"]:721: in function <BasicMinimap\BasicMinimap.lua:720>

Locals:
self = <unnamed> {
 0 = <userdata>
}
text = "The Idyllia"
pvpType = "sanctuary"
(*temporary) = nil
(*temporary) = "attempt to call a nil value"
GetMinimapZoneText = <function> defined =[C]:-1
zoneTextFont = <unnamed> {
 0 = <userdata>
}
GetZonePVPInfo = <function> defined =[C]:-1
frame = BasicMinimap {
 0 = <userdata>
 PET_BATTLE_CLOSE = <function> defined @BasicMinimap\BasicMinimap.lua:679
 ADDON_LOADED = <function> defined @BasicMinimap\BasicMinimap.lua:684
 mask = <unnamed> {
 }
 backdrop = <unnamed> {
 }
 blizzButtonPositions = <table> {
 }
 coords = <unnamed> {
 }
 LOADING_SCREEN_DISABLED = <function> defined @BasicMinimap\BasicMinimap.lua:702
 CALENDAR_ACTION_PENDING = <function> defined @BasicMinimap\BasicMinimap.lua:663
 PET_BATTLE_OPENING_START = <function> defined @BasicMinimap\BasicMinimap.lua:674
 db = <table> {
 }
 clock = <unnamed> {
 }
 HideButtons = <function> defined @BasicMinimap\BasicMinimap.lua:34
 CALENDAR_UPDATE_PENDING_INVITES = <function> defined @BasicMinimap\BasicMinimap.lua:663
}

**Comment by funkydude** [comment]
I didn't want to return to Oribos currently to test, but looking at the code, I believe it was unrelated.
Seems that you were just coincidentally having the mouse over the ZoneText when reloading.
