### ISSUE TITLE
Feature Request: Toggle Scoreboard Click

### ISSUE THREAD

**Issue by nolangerner** [funkydude/BasicMinimap#57]
I think it would be a nice addition to be able to open up the battleground and arena scoreboard with a customizable click similar to the calendar.

**Comment by funkydude** [comment]
I don't have anything against expanding the options for minimap clicks, but why the scoreboard? BasicMinimap has no option to hide the LFG button, so it's always shown. So why click the minimap instead of the button?

**Comment by nolangerner** [comment]
You're right that it's a bit of a funky request, but I personally hide the LFG button (using another addon) because I don't really like the aesthetics of it. Usually I just key bind  the scoreboard function, but using a quick mouse button would be a nice change.
