### ISSUE TITLE
Feature Request: Sliders for Compass scale and alpha

### ISSUE THREAD

**Issue by Dreamjammer** [funkydude/BasicMinimap#59]
When you change the size of the minimap and you have rotate on, it can cause the compass to no longer be along the outside of the minimap. It would be nice to have some options to scale it up to fit the new size. Maybe it could be done automatically, but I think whether one likes the marks and the "N" to be inside or outside is a matter of taste, so having a slider and letting people adjust to taste might be the best option here. And while we're at it, have an alpha slider for if one wants the "N" and notches to the somewhat see-through (this also helps with the fact that at full opacity, upscaled, the compass texture looks a bit naff).

fwiw, I threw these lines into a quick addon to adjust it myself, so this is kinda what I'm thinking, except without the values being hardcoded, of course:

`MinimapCompassTexture:SetScale(1.75)`
`MinimapCompassTexture:SetAlpha(0.5)`
`local point, relativeTo, relativePoint, x, y = MinimapCompassTexture:GetPoint()`
`MinimapCompassTexture:SetPoint(point, relativeTo, relativePoint, 0, 0)`

This fits my size 320 minimap pretty well. The last bit with SetPoint was needed because, for some reason the compass is offset a bit by default, and it's really obvious when you blow it up from its default (0.7) scale.

**Comment by funkydude** [comment]
Closing this since the compass was removed.
