### ISSUE TITLE
Can I ask for a new border texture?

### ISSUE THREAD

**Issue by zh648990** [funkydude/BasicMinimap#6]
I like this map plugin very much, can I make a request, add a border material, because I think this material is very cool.
Thank you very much.
[map.zip](https://github.com/funkydude/BasicMinimap/files/1994839/map.zip)

**Comment by funkydude** [comment]
The border around this map doesn't have a texture, it's a simple color. It's unlikely I will ever add texture support to this addon.

**Comment by zh648990** [comment]
OK Thank you

At 2018-05-11 23:25:41, "funkydude" <notifications@github.com> wrote:


The border around this map doesn't have a texture, it's a simple color. It's unlikely I will ever add texture support to this addon.
