### ISSUE TITLE
Find Herb / Find Minerals Icon not showing up on minimap

### ISSUE THREAD

**Issue by MrElvisYo0** [funkydude/BasicMinimap#61]
## Describe the problem
it does not show Find Herbs or Find Minerals in the newest version

### What steps will reproduce the problem?

1.  click the spells and it should show up on your minimap top left somewhere, but right now it does not show up
2.  
3.

**Comment by funkydude** [comment]
The tracking button is hidden in all versions. You can middle click the minimap to open the menu or rebind it in the options.
![image](https://user-images.githubusercontent.com/16833/119205487-3f994b80-ba90-11eb-81a9-5bef1b148980.png)

**Comment by Calzeru** [comment]
How come? As a hunter it is very useful to show what tracking you currently have active. For the entirety of classic the tracking button was showing just fine, but after updating to TBC version it is gone. Will you please reconsider the decision to remove it?
