### ISSUE TITLE
Request: Add the Tracking Button to the TBC version.

### ISSUE THREAD

**Issue by perringaiden** [funkydude/BasicMinimap#62]
With tracking now included, being able to change the currently tracked items is part of the minimap instead of just a spell.  However, the BasicMinimap does not appear to show it.

**Comment by funkydude** [comment]
One of the main features of this addon is minimap clicks for ease of use. You can middle click the minimap to open the tracking menu, for example. Please close this if this resolves your issue.

**Comment by moontail7** [comment]
Second this request. Love the addon but would love to have the circular icon back for tracking. Thank you!

**Comment by moontail7** [comment]
Second this request. Love the addon but would like to have the circular icon back for tracking. Thank you!

**Comment by perringaiden** [comment]
> One of the main features of this addon is minimap clicks for ease of use. You can middle click the minimap to open the tracking menu, for example. Please close this if this resolves your issue.

Knowing this solved my issue here.
