### ISSUE TITLE
Buttons appear in Circle Layout

### ISSUE THREAD

**Issue by perringaiden** [funkydude/BasicMinimap#63]
I use the map in a Square format.

However since 2.5.2, on login, the buttons around the map appear in a circle layout, overlapping the map itself, until I open the config and switch from Square to Circle then back.

**Comment by Seguaro** [comment]
Same issue. Would be nice if the buttons retained their positions after UI reload instead of going back to circle layout.

**Comment by funkydude** [comment]
@perringaiden @Seguaro This isn't something I can reproduce so it's most likely another addon causing it. Disable all your other addons and the problem will likely be resolved. You can re-enable addons in batches until the issue returns, to make it easier to find out what addon is causing it.

If you find out, post here for future people reading it.
