### ISSUE TITLE
Season of Mastery Classic Era support

### ISSUE THREAD

**Issue by cralor** [funkydude/BasicMinimap#64]
## Describe the problem
Errors associated with CALENDAR event registration causing addon not to load

### What steps will reproduce the problem?

1.  Download BCC or Classic client to Season of Mastery Classic Era client
2.  Launching game

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
N/A

### What version of the addon are you using? (Stating 'latest' is not useful)
v2 bcc/v4 classic

### Do you have an error log of what happened?
```
9x BasicMinimap\BasicMinimap-v9.1.0.lua:699: Attempt to register unknown event "CALENDAR_UPDATE_PENDING_INVITES"
[string "=[C]"]: in function `RegisterEvent'
[string "@BasicMinimap\BasicMinimap-v9.1.0.lua"]:699: in main chunk

Locals:
(*temporary) = BasicMinimap {
 0 = <userdata>
 CALENDAR_UPDATE_PENDING_INVITES = <function> defined @BasicMinimap\BasicMinimap.lua:691
 CALENDAR_ACTION_PENDING = <function> defined @BasicMinimap\BasicMinimap.lua:691
 blizzButtonPositions = <table> {
 }
}
(*temporary) = "CALENDAR_UPDATE_PENDING_INVITES"
```

**Comment by funkydude** [comment]
@cralor This is now resolved. Thanks to improvements in WoW, we now have the ability for addons to support multiple versions of WoW in 1 addon package. This system has now been implemented in the latest version of BasicMinimap which will make it far easier to maintain classic going forward.
