### ISSUE TITLE
Text Clock disappears after WoW restart

### ISSUE THREAD

**Issue by loquatdonut** [funkydude/BasicMinimap#66]
### What steps will reproduce the problem?

Occurs with any font

Set Text Clock to appear (settings in the attached screenshot)

Text clock disappears after WoW restart. 

I have to select another font to make it visible.

### What version of the addon are you using? (Stating 'latest' is not useful)

2.5.1

### Do you have an error log of what happened?

No errors

### Any additional information? (example: WoW language if not English)

English
![WoWScrnShot_010122_165547](https://user-images.githubusercontent.com/60828832/147854439-8f020f68-72e2-4a64-999d-aa7694979c33.jpg)
![WoWScrnShot_010122_165826](https://user-images.githubusercontent.com/60828832/147854441-e6dc457b-f8cb-42a9-ad61-141a1803fefb.jpg)

**Comment by funkydude** [comment]
@loquatdonut This isn't something I can reproduce so it's most likely another addon causing it. Disable all your other addons and the problem will likely be resolved. You can re-enable addons in batches until the issue returns, to make it easier to find out what addon is causing it.

If you find out, post here for future people reading it.
