### ISSUE TITLE
[BC Classic] [Lua Error] AddOn 'BasicMinimap' tried to call the protected function 'GuildControlSetRank()'

### ISSUE THREAD

**Issue by boktai1000** [funkydude/BasicMinimap#68]
## Describe the problem
```
2x [ADDON_ACTION_FORBIDDEN] AddOn 'BasicMinimap' tried to call the protected function 'GuildControlSetRank()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GuildControlSetRank'
[string "@Interface_TBC\FrameXML\FriendsFrame.lua"]:2756: in function `GuildControlPopupFrameDropDownButton_ClickedRank'
[string "@Interface_TBC\FrameXML\FriendsFrame.lua"]:2508: in function `GuildControlPopupFrame_Initialize'
[string "@Interface_TBC\FrameXML\FriendsFrame.lua"]:966: in function `FriendsFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
```

### What steps will reproduce the problem?

1.  Had Guild pane/list Opened in raid
2.  Previously was looking at different levels of tracking for things, like Reagents, etc before opening Guild pane/list
3.  It may have popped up in combat, can't remember for sure

### What version of the addon are you using? (Stating 'latest' is not useful)

v9.2.3 for BC Classic

**Comment by funkydude** [comment]
@boktai1000 If you `/reload` UI and follow the reproduction steps, does it happen every time?

Also how many times has this happened, and did it only just start happening in the new version?

**Comment by funkydude** [comment]
No response, closing.
