### ISSUE TITLE
Changing scale changes icon sizes

### ISSUE THREAD

**Issue by birgwow** [funkydude/BasicMinimap#7]
I'm having an issue where if I change the scale of the minimap all the minimap icons get super big too (such as quests, flightpath, battle pets, mining nodes). 

Is there any way to change the size of the map without touching the size of these icons, or changing the size of them?

Thank you in advance :)

**Comment by funkydude** [comment]
This is how scaling works, it's always been this way, I don't envision changing it.

I don't know what you mean by nodes become super big, it sounds like an over exaggeration to me.
Everything scales slowly as you move the slider, even at large scales nothing seems unreasonable to me.
Perhaps show your problem with a screenshot.

**Comment by funkydude** [comment]
If you've already edited the addon, why not just change the scale option to a size option?

**Comment by birgwow** [comment]
I don't know lua, I just get what I want through trial and error. Making it a rectangle took a long time :P

So I don't know what you mean by that I'm afraid. But it's no big deal really, just wanted to know if there was a quick fix.

**Comment by SexualRhinoceros** [comment]
Gotta agree here I had to use MoveAnything to rescale the items which would be a pretty simple job with just an offset. Would make the addon infinitely more attractive to people who want the other awesome features already built in but want a larger map overall.

My only remaining issue is the scaling of the actual POI on the map but I'm sure theres an option to rescale those too somewhere, I just haven't been bothered to look.

**Comment by funkydude** [comment]
Removed the scale option and replaced with a size option. I doubt it will work with a hacked in mask from another addon but that's a different issue more in line with requesting additional shapes.
