### ISSUE TITLE
Request: More Button Hide Options

### ISSUE THREAD

**Issue by Spiderkeg** [funkydude/BasicMinimap#78]
Any chance more options can be included to hide the mail icon, garrison icon, covenant icon, etc.?

**Comment by funkydude** [comment]
The "garrison" and "covenant" are the same icon called "missions" and you can already hide it. In regards to mail, just open your mail to hide it..?

**Comment by glassleo** [comment]
I would also like an option to hide the unread mail icon. It's the only minimap button the addon won't let me hide.

I use a WA to display if I have unread mail elsewhere so I don't want it on my minimap as well.

**Comment by Spiderkeg** [comment]
Thanks for this update.
