### ISSUE TITLE
10.0.5 bug upon loading into game

### ISSUE THREAD

**Issue by wjakobsmeier** [funkydude/BasicMinimap#81]
### What steps will reproduce the problem?

1.  log in to the game 10.0.5
2.  BugSack stored bug:
```1x Usage: self:SetParent([parent])
[string "=[C]"]: in function `SetParent'
[string "@BasicMinimap/BasicMinimap.lua"]:652: in function <BasicMinimap/BasicMinimap.lua:500>
[string "@BasicMinimap/BasicMinimap.lua"]:883: in function <BasicMinimap/BasicMinimap.lua:874>

Locals:
(*temporary) = "Usage: self:SetParent([parent])"```
4.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)


### What version of the addon are you using? (Stating 'latest' is not useful)


### Do you have an error log of what happened?


### Any additional information? (example: WoW language if not English)

**Comment by Knaledge** [comment]
Further, there are now new frame elements (like location, mail indicator, and calendar button) that are not currently in control of BasicMiniMap. In other words, 10.0.5 introduced new minimap elements that BMM is not handling - and some of this is leading to the reported taint issues here.

**Comment by funkydude** [comment]
Mail and calendar are ancient and already handled by the addon.
Not sure what you mean by location, please open a separate issue with an explanation.
