### ISSUE TITLE
Support for the work order icon

### ISSUE THREAD

**Issue by cremor** [funkydude/BasicMinimap#83]
## Describe the problem
If you have a personal work order pending an icon is shown at the minimap - similar to the icon for new mail. It seems like this icon isn't supported by the addon. It's not attached to the minimap border and there is no option to move it.

### What steps will reproduce the problem?

1.  Have a pending personal work order.
2.  Check how the icon is shown.
3.  Try to move the icon in the addons options.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![grafik](https://user-images.githubusercontent.com/116314/220442697-506456b1-d39b-4d87-999a-09e3f19c6e06.png)

### What version of the addon are you using? (Stating 'latest' is not useful)
v10.0.8

### Do you have an error log of what happened?
No error

### Any additional information? (example: WoW language if not English)
German WoW client

**Comment by funkydude** [comment]
Yup, this is going to need to be made into a separate addon button
