### ISSUE TITLE
The minimap buttons for mail and bg, dont stay where u move them after a reload

### ISSUE THREAD

**Issue by aaaror** [funkydude/BasicMinimap#90]
## Describe the problem

The minimap buttons for mail and bg, dont stay where u move them after a reload or change of zone

on wow SoD, 1.15 client

**Comment by funkydude** [comment]
Then you most likely have another addon moving them. Try disabling all your addons except BasicMinimap, does it work then?

If it does, gradually re-enable your addons until you find the culprit, and let us know what caused it.

**Comment by funkydude** [comment]
1. Addons that use custom code to create their minimap buttons are not supported and never will be. If you want them to be supported, ask their authors to move from custom code to the "LibDBIcon" universal library which virtually every addon uses now to be compatible with each other.

2. Same as 1.

3. I'm not even sure how you are getting all those arrows, so I'm going to assume it's an addon drawing them incorrectly. Once again I ask that you disable your other addons.
Below is an example of my minimap on classic, scaled up, showing the Questie loot bags correctly at the edge of the map.
![image](https://github.com/funkydude/BasicMinimap/assets/16833/16ceb089-9fad-4325-b304-076533eb87a0)

4. Same as 1.

**Comment by funkydude** [comment]
No response, closing.
