### ISSUE TITLE
Clicks options are greyed out and not working except open map

### ISSUE THREAD

**Issue by Master0fEvil** [funkydude/BasicMinimap#91]
## Describe the problem
title, issue persists after disabling all other addons

### What steps will reproduce the problem?

1.  install basic minimap
2.  ????
3.  profit

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![2023-12-17 05_49_55-World of Warcraft](https://github.com/funkydude/BasicMinimap/assets/22616684/9e6322c7-98d5-441d-9fe0-f7fe22ee091f)

### What version of the addon are you using? (Stating 'latest' is not useful)
10.2.1

### Do you have an error log of what happened?
no

**Comment by funkydude** [comment]
You're playing on classic, where those things don't exist. They are retail only features. If you want them, ask Blizz to add them.
