### ISSUE TITLE
Problem with minimap shape and hide addon buttons when first logging in.

### ISSUE THREAD

**Issue by linusalpsten** [funkydude/BasicMinimap#92]
## Describe the problem
When i login some of my saved options are not applied propperly, not all options. I am not sure exactly which options but 2 that i know are not working propperly for me is "Shape" and "Hide addon buttons" and one option that i seems to be working is "Scale". My options seems to be saved properly when i look in the options menu (/bmm) and in my accounts saved variables.
My chosen shape is square and i choose to show addon buttons, bellow is a snipped from BasicMinimap.lue in my saved variables.

`["Default"] = {
			["hideAddons"] = false,
			["lock"] = true,
			["coordPrecision"] = "%.1f, %.1f",
			["size"] = 180,
			["zoneTextConfig"] = {
				["y"] = 0,
			},
		}`
Here is an image of how my minimap and buttons look when i log in. My buttons are in a minimap button container addon called "MinimapButtonButton" but the buttons are hidden until i hover over them even without "MinimapButtonButton".
![image](https://github.com/funkydude/BasicMinimap/assets/21305600/db176eab-5a5b-440b-9c3e-8342635e48c2)

### What steps will reproduce the problem?

1.  Every time i log in on any character the minimap and buttons look like the screenshot above, it gets "fixed" if i toggle the shape from square and back to square and toggle hide addon buttons.
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
BasicMinimap-v10.2.3

### Do you have an error log of what happened?
No lua errors

### Any additional information? (example: WoW language if not English)
I am considering trying to fix the problem my self and make a pull request, unless some one knows how to fix this problem easily, but i am not familiar with lua or wow api, but from reading your code it looks approachable enough.

**Comment by funkydude** [comment]
This happens when you have another addon interfering, probably something like Leatrix. Try disable all your other addons and only load BasicMinimap.
