### ISSUE TITLE
Issues after 10.2.6 upgrade

### ISSUE THREAD

**Issue by jleafey** [funkydude/BasicMinimap#94]
## Describe the problem
After the upgrade, BMM is not behaving the same,. and some settings no longer work as they did.  The mouse-button actions are no longer working and a Lua exception is thrown when I try to move the Zone Text, Clock, or Coordinates positions using the settings page.  Problem does not prevent gameplay, but the occasional alerts from BugGrabber/BugSack are a bit annoying. :^)

### What steps will reproduce the problem?

1.  Log into retail after 10.2.6 update.  Problem occurs shortly after logging in.
2.  In addition, a Lua exception is thrown when I try to move the Zone Text, Clock, or Coordinates positions using the settings page
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
General tab from settings:
![image](https://github.com/funkydude/BasicMinimap/assets/40215264/a49ffc02-873c-4897-bf6a-b7b193715353)
Clicks tab:
![image](https://github.com/funkydude/BasicMinimap/assets/40215264/98dadb70-3aff-4fd8-b9a5-8f290028bbfc)
Buttons tab:
![image](https://github.com/funkydude/BasicMinimap/assets/40215264/2f562a8e-fc08-4f28-8c17-a903c8567d2e)
Text tab:
![image](https://github.com/funkydude/BasicMinimap/assets/40215264/26a33507-19da-406c-a097-0d8af4d0eedd)
Nothing useful on Profiles tab.
Here is a clip showing how the minimap looks now:
![image](https://github.com/funkydude/BasicMinimap/assets/40215264/cf22970a-daa4-4b7b-b637-99015a2092ec)

### What version of the addon are you using? (Stating 'latest' is not useful)
v10.2.3

### Do you have an error log of what happened?
Here is the only error that has shown up in BugSack so far:

6x Usage: self:SetParent([parent])
[string "=[C]"]: in function `SetParent'
[string "@BasicMinimap/BasicMinimap.lua"]:652: in function <BasicMinimap/BasicMinimap.lua:500>
[string "@BasicMinimap/BasicMinimap.lua"]:883: in function <BasicMinimap/BasicMinimap.lua:874>

Locals:
(*temporary) = "Usage: self:SetParent([parent])"

### Any additional information? (example: WoW language if not English)
Before 10.2.6, the clock and coordinates were at the bottom of the minimap.
If I try to change the Coordinates location using the sliders, I get a Lua exception:

46x BasicMinimap_Options/Options.lua:944: attempt to index field 'coords' (a nil value)
[string "@BasicMinimap_Options/Options.lua"]:944: in function <BasicMinimap_Options/Options.lua:942>
[string "=[C]"]: ?
[string "@Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "@Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:888: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:876>
[string "=[C]"]: ?
[string "@Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-Slider.lua"]:65: in function <...dOns/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Slider.lua:56>

Locals:
_ = <table> {
 1 = "text"
 2 = "coords"
 uiName = "AceConfigDialog-3.0"
 uiType = "dialog"
 3 = "y"
 options = <table> {
 }
 type = "range"
 option = <table> {
 }
 appName = "BasicMinimap"
}
value = -11
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'coords' (a nil value)"
map = BasicMinimap {
 0 = <userdata>
 PET_BATTLE_CLOSE = <function> defined @BasicMinimap/BasicMinimap.lua:875
 ADDON_LOADED = <function> defined @BasicMinimap/BasicMinimap.lua:880
 blizzButtonNicknames = <table> {
 }
 backdrop = Texture {
 }
 LOADING_SCREEN_DISABLED = <function> defined @BasicMinimap/BasicMinimap.lua:898
 CALENDAR_ACTION_PENDING = <function> defined @BasicMinimap/BasicMinimap.lua:859
 PET_BATTLE_OPENING_START = <function> defined @BasicMinimap/BasicMinimap.lua:870
 db = <table> {
 }
 Layout = <function> defined @BasicMinimap/BasicMinimap.lua:670
 mask = MaskTexture {
 }
 CALENDAR_UPDATE_PENDING_INVITES = <function> defined @BasicMinimap/BasicMinimap.lua:859
}

**Comment by funkydude** [comment]
Should be fixed now, ty!

**Comment by jleafey** [comment]
yes, that appears to have resolved the issue.  Thanks for a great add-on!  Here's a screenshot from after the update:
![image](https://github.com/funkydude/BasicMinimap/assets/40215264/92e6b78e-fb2e-48c7-884b-1baeb5b788c6)
