### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by SanUI** [funkydude/BasicMinimap#95]
Hey there!

From the toc file:

```
## X-License: All Rights Reserved: You are free to fork and modify on GitHub, please ask us about anything else.
```

I'd like to inquire more about "anything else" :)

I'd like to include BasicMinimap in my collection [`SanUI`](https://www.wowinterface.com/downloads/info18562-SanUI.html), which is hosted on [github as well](https://github.com/SanUI/SanUI). Does that mean I could simply include a certain version of your addon as a subfolder? I'd surely give credit appropriately, but I'd very much like to ship BasicMinimap with SanUI (on wowinterface.com as well).

I'm not planning any internal modifications for now, but if I wanted to, would that be fine? Otherwise, what would I need to do for it to be fine? What about external modifications?

Thanks for making BasicMinimap in any case!

**Comment by funkydude** [comment]
Yes you can, thank you for asking!
