### ISSUE TITLE
Unrecognized XML values

### ISSUE THREAD

**Issue by Darwand** [funkydude/BasicMinimap#96]
## Describe the problem
Upon loading the addon 10 separate errors are thrown as Unrecognized XML attribute

### What steps will reproduce the problem?

1.  Load the addon

### What version of the addon are you using? (Stating 'latest' is not useful)
v10.2.7

### Do you have an error log of what happened?
`MinimapButtonFrame/MinimapButtonFrame.xml:13 Unrecognized XML attribute: val`
`MinimapButtonFrame/MinimapButtonFrame.xml:13 Unrecognized XML: AbsValue`
`MinimapButtonFrame/MinimapButtonFrame.xml:12 Unrecognized XML: TileSize`
`MinimapButtonFrame/MinimapButtonFrame.xml:10 Unrecognized XML attribute: val`
`MinimapButtonFrame/MinimapButtonFrame.xml:10 Unrecognized XML: AbsValue`
`MinimapButtonFrame/MinimapButtonFrame.xml:9 Unrecognized XML: EdgeSize`
`MinimapButtonFrame/MinimapButtonFrame.xml:8 Unrecognized XML attribute: tile`
`MinimapButtonFrame/MinimapButtonFrame.xml:8 Unrecognized XML attribute: edgeFile`
`MinimapButtonFrame/MinimapButtonFrame.xml:8 Unrecognized XML attribute: bgFile`
`MinimapButtonFrame/MinimapButtonFrame.xml:8 Unrecognized XML: Backdrop`

**Comment by funkydude** [comment]
Thanks for your report but it has nothing to do with my addon. The addon in question is called "MinimapButtonFrame"
