### ISSUE TITLE
Feature Request: Daily Reset Time

### ISSUE THREAD

**Issue by Zaazu** [funkydude/BasicMinimap#98]
![image](https://github.com/user-attachments/assets/4408126d-41a3-4836-adad-6ecf5105b288)

Is there any chance we could get an additional field in the Time Info that shows the daily quest reset time?

**Comment by Zaazu** [comment]
Another way could be a countdown with HH:MM like so:

![image](https://github.com/user-attachments/assets/aaf06938-22dc-4901-8a70-237cd1bef9c2)

Any thoughts? cheers

**Comment by funkydude** [comment]
It looks like <https://warcraft.wiki.gg/wiki/API_GetQuestResetTime> is available so this should theoretically be doable

**Comment by Zaazu** [comment]
Very clean implementation thanks. Funnily enough I just forked and was about to make a pull request haha

**Comment by funkydude** [comment]
No harm in learning something new, appreciate the effort :)
