### ISSUE TITLE
Feature Request: Add Option to Set Minimap Strata

### ISSUE THREAD

**Issue by Spiderkeg** [funkydude/BasicMinimap#99]
Can a simple downdown option be added that allows for the setting of the Minimap strata (i.e. High, Low, Background, etc.)?  I generally have my minimap above some layout assets, but can toggle the Show/Hide via a broker button.

---------

If not an option, can I get instructions on how to change the strata manually in the LUA code?  Thanks.

**Comment by funkydude** [comment]
No plans for this, sorry!

**Comment by Spiderkeg** [comment]
> No plans for this, sorry!

That's fine... any chance you could give me instructions on how to edit this myself?

**Comment by Zaazu** [comment]
> That's fine... any chance you could give me instructions on how to edit this myself?

Hi, I made you a WeakAura that edits the strata and frame level. The benefit of using a WeakAura is that you can keep BasicMinimap updated and your strata fix will always work.

To edit the strata, just open the trigger and edit the code where it says ```local frameStrata = "HIGH" ```

Let me know if there are any issues and I might be able to fix them :)

https://wago.io/OB3u84Hgd
